name: base_uri
description: A tiny wrapper around Uri to easily define a base uri that is reusable for all your endpoints. It also adds a version parameter.
version: 1.0.0
repository: https://github.com/thomasthiebaud/base_uri

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
