name: base_uri
description: A tiny wrapper around Uri to easily define a base uri that is reusable for all your endpoints. It also adds a version parameter.
version: 0.1.1
repository: https://github.com/thomasthiebaud/base_uri

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  test: ^1.15.4
